### ISSUE TITLE
Failed to query midi devices.

### ISSUE THREAD

**Issue by GhostFenixx** [ianespana/ShawzinBot#1]
On startup of .exe file i'm getting:
![ExeResult](https://user-images.githubusercontent.com/10713959/64080372-0fc67500-ccfc-11e9-8a69-b3ee9f69ac84.png)
On startup of a main .ahk script i'm getting(AHK itself is installed, and 2 other scripts launched with no issue):
![AhkResult](https://user-images.githubusercontent.com/10713959/64080408-87949f80-ccfc-11e9-9c44-af1e005cdef3.png)

As a midi i use USB MIDI interface, similiar to this: 
https://www.ebay.com/itm/USB-MIDI-Interface-Cable-PC-to-Novation-25-SL-MK2-USB-MIDI-Controller-Keyboard-/161466292936
Midi is detectable and works in sound editing programs(Such as LMMS), and Internet Browsers.
Any tip?

**Comment by lilggamegenius** [comment]
Can confirm i get the exact same error on Windows 10. Tested with a USB MIDI device and with LoopBe1

**Comment by Pawel-Dymek** [comment]
same problem here :c

**Comment by ianespana** [comment]
Someone mentioned the same issue on Reddit. I need to figure this one out

**Comment by GhostFenixx** [comment]
If you may need a test dummy feel free to contact me via Discord: GhostFenixx©#5032

**Comment by LiuShujushi** [comment]
same issue

**Comment by ianespana** [comment]
Alright, so, I'm working on a new version that doesn't use Autohotkey (Uses C#). It's almost ready, I just need to get warframe to react to the inputs

**Comment by lilggamegenius** [comment]
How are you sending the inputs? Are you sending it as a key like the AHK version?
you could try using user32.dll to send the keys

**Comment by ianespana** [comment]
@lilggamegenius Yes. I'm currently using WPF, so I can't use `SendKeys.SendWait`.
I'm going to try it out with user32's `PostMessage`, however it also has to be able to send mouse inputs, as that's what changes frets

**Comment by lilggamegenius** [comment]
maybe you can try that and add this extern function from the same dll? https://stackoverflow.com/a/2416762

**Comment by ianespana** [comment]
Could work. I've been doing some research and from what I gather I also have to get around DirectX, since it also proceses inputs in a different way.
It's a bit late now for me, but I'll look at this tomorrow

**Comment by lilggamegenius** [comment]
Can you push what you have to a test branch? i can try doing some testing on my own.

**Comment by ianespana** [comment]
Yup, done. Inside `ActionManager.cs` you'll find all of the `user32.dll` functions I've already implemented, as well as some of my (not yet finished) code.
`OnNoteEvent` is the method where note events will be processed, and the note ID should be passed to transform it to a key press

**Comment by ianespana** [comment]
@lilggamegenius You can make push requests to the `Testing` branch as you please, but I'll keep the development branch as clean as possible

**Comment by lilggamegenius** [comment]
Made a PR of my current changes but not ready to be merged yet. Managed to get warframe to react to input but still needs some work.
#4

**Comment by ianespana** [comment]
Issue no longer relevant to this new version. Closing
