### ISSUE TITLE
volume in c# version

### ISSUE THREAD

**Issue by noobchief** [ianespana/ShawzinBot#10]
Ahk version somehow was able to translate different volume of specific track of midi file (it useful you can adjust one instrument for better sound). Is it possible in C# version?

**Comment by ianespana** [comment]
The way that happened was just sending more than one keypress in quick succession. I can add it back in, but honestly saw no point in doing so.
If more people request it I'll add it to the next release

**Comment by noobchief** [comment]
Ok, thank you. It would be great as an option if you'll add it in the future.
