### ISSUE TITLE
Strings, Scales and Vibrato are working but Frets are not

### ISSUE THREAD

**Issue by Pawel-Dymek** [ianespana/ShawzinBot#12]
Hi, I love concept of your bot and thanks for creating it <3

unfortunately it's not working for me, because of the problem described in the title.
I've tried different MIDI files and changing keybindings to N, L, M, as suggest in now closed thread, but nothing works :c 

Thanks in advance for any help

**Comment by Valhyra** [comment]
I'm quite having the same issue.. I have no idea how to fix it

**Comment by ianespana** [comment]
Use the default inputs, and make sure you are running in admin mode

**Comment by Pawel-Dymek** [comment]
> Use the default inputs, and make sure you are running in admin mode

Admin mode helped, thanks for the feedback <3
