### ISSUE TITLE
Bot fails to press frets

### ISSUE THREAD

**Issue by Cenakaze** [ianespana/ShawzinBot#14]
as mentioned above. I tried to set the frets to mouse buttons (default keys now are left, down and right arrow keys), ran the bot w/ admin and still can't get it to work

**Comment by Cenakaze** [comment]
also tried N L M, no sauce

**Comment by ianespana** [comment]
Use default controls

**Comment by Zeilos** [comment]
Actually I've been having the same issue. Tried with defaults and ran as administrator as per the closed requests. I also tried resetting the controls and redownloading the bot. Was waiting for a reply on this thread but saw it got closed.
