### ISSUE TITLE
Incorrect Transposing from note E6 onwards

### ISSUE THREAD

**Issue by Kisutora** [ianespana/ShawzinBot#16]
Starting from E6 the transposing is incorrect. (See picture)
![FL64_YkVsvj6EGN](https://user-images.githubusercontent.com/22685232/64904823-285d6480-d6d8-11e9-9312-a01a6d5b95b9.png)

**Comment by namidairo** [comment]
https://github.com/ianespana/ShawzinBot/blob/master/ShawzinBot/ActionManager.cs#L163

Should be - 15 to correctly offset down to the C, probably.

**Comment by ianespana** [comment]
Fixed the formula used to transpose in commit 7b5442ea4dda601881dac1f9ff62d28bc3bd3793. Issue closed
