### ISSUE TITLE
[Feature Request] Button to reset to chromatic scale

### ISSUE THREAD

**Issue by VanStorm** [ianespana/ShawzinBot#20]
It would be nice to have a button which we can click to signalize the bot that the Shawzin got set to "chromatic" scale again.
I use Ableton Live to send midi data to the shawzin bot but this would work with any other external midi source as well. When you restart the sequence and set the shawzin back to chromatic scale it tries to work from the last used scale. So the only way to start again from chromatic scale is restarting the bot.

An additional idea would be using an unused midi note like c-1 (midi note code 0) as a reset note as well.

**Comment by ianespana** [comment]
I like using code 0 as a reset. I'll also add a reset button to the program, and I may just add a current scale indicator so you don't necessarily need to reset the scales
