### ISSUE TITLE
Weird Issue with Frets.

### ISSUE THREAD

**Issue by GenGuard** [ianespana/ShawzinBot#21]
Might be unrelated to the bot itself but for some reason it doesn't use the Frets but it does send the input, so the problem might be with me or Warframe.
I do start the bot as admin, have the controls on default and can see that the input does come in, since when i open the menu while playing something it is selecting through the menu-tabs like when you use the arrow keys.
I don't have a way to see if the input itself isn't send anymore (which i don't think) or if my game just ignores the input for some reason.

**Comment by ianespana** [comment]
"It doesn't use the frets"
If by that you mean you don't see the hand on the frets moving, that's totally normal. If your song is playing correctly there's no reason to worry
