### ISSUE TITLE
Shawzinbot sometimes goes out of tune when I stop it mid song and have to restart it to get it back in tune

### ISSUE THREAD

**Issue by WMan22** [ianespana/ShawzinBot#22]
Sometimes I stop a midi mid song so I can restart it from the beginning, but recently it has been going out of tune when I try to play it from the beginning, even if I switch back to chromatic again. This didn't happen before the Yo scale was added, I don't think. 

Restarting the program entirely fixes this, but it's definitely something you might wanna check into.

**Comment by ianespana** [comment]
It's a know issue, has to do with the inability to restart the current scale. I haven't had time to fix this yet, but I will at some point
