### ISSUE TITLE
Sounds very, very weird.

### ISSUE THREAD

**Issue by Kumicoo** [ianespana/ShawzinBot#23]
No matter what midi i put in, no matter what octave i choose, it always sounds like some weird nightmare. I tried "Awesome God", the popular song. It doesnt work, at all. It sounds like circus music straight out of hell. Is the bot broken?

**Comment by Rareat** [comment]
Any song sounds awful if you download a midi and use it straight without simplifying it. I use fl studio to remove drums, cut out some bass and other instruments that may interfere with the actual melody. You have 1 guitar with 3 strings, not a whole orchestra... keep that in mind. Songs like Back in Black by AC/DC, La Grange by ZZ Top and Money for nothing by Dire Straits are amazing. If you leave only vocals, guitar and bass guitar playing.

**Comment by Kumicoo** [comment]
I have a very simple midi. Made in Online sequencer. Also tried FL Studio. No overlapping, only 1 lead sound. It still sounds very , very weird. I am 100% sure my midi is not the problem. Every online midi player recognizes it, it's rendered as an SFM, media player plays it, synthesia plays it. Shawzin bot? Sounds like horror circus.

**Comment by ianespana** [comment]
Have you set the correct starting scale...?
