### ISSUE TITLE
Shawzin variation compatibility

### ISSUE THREAD

**Issue by niktr** [ianespana/ShawzinBot#29]
an update is needed to improve the compatibility with the newly added Shawzins.
Currently im forced to Edit songs and scale up or down entire rows in order for them to work.

**Comment by ianespana** [comment]
Will look into this asap, but AFAIK all shawzins use the exact same scales

**Comment by niktr** [comment]
its been a while, i did some poking around.
The scales might be the same, but the sound produced doesn't match. DE's scale isn't exactly accurate to MIDI file scales.
when it rounds up or down, the notes most of the time end up being on the same string making some songs sound like you're just spamming 1 note.
For example, Rage from Quake 2. I had to push some notes up and some notes down (increase the difference value) so it doesn't round them on the same string.
if that makes sense...
