### ISSUE TITLE
Lastest release is 5 commits behind, doesnt use the arrow controls

### ISSUE THREAD

**Issue by ajuanjojjj** [ianespana/ShawzinBot#32]
Possibly because of the outdated build, the lastest release does not use the sky/earth/water frets with the arrows, I'm assuming it still tries to use the mouse buttons, making it sound terrible.

**Comment by ianespana** [comment]
Yes, release is behind, I need to upload the latest compiled version. As for frets, it uses arrows, so there's something else wrong with your setup (probably wrong initial scale)

**Comment by ajuanjojjj** [comment]
Just tested it again (It had been ages since i last used it so maybe it was just that), and confirmed that initial scale is not the problem, and the frets are not being used. Maybe it's something else interfering with the program? Anything should look for?

Video showing the frets not working (Fingers not moving)
https://i.gyazo.com/b0c6296ff97bf0493e191a14040de997.mp4

**Comment by ianespana** [comment]
Frets are working just fine. The reason you don't see the fingers moving is because the key presses are sent real fast, but I can assure you they're happening

**Comment by ajuanjojjj** [comment]
Sorry to disagree, but even if the problem is not the frets (was my main assumption because of the lack of _any_ movement on the fingers, the resulting sound in game is miles apart from what it's supposed to be. Ive uploaded a test using a C Major midi to keep it simple, but i wouldnt mind trying other stuff out if needed (Maybe it's some random driver intercepting the presses, or DE changed something, or whatever)

[Shawzin Report.zip](https://github.com/ianespana/ShawzinBot/files/5264226/Shawzin.Report.zip)

**Comment by ianespana** [comment]
Update to the latest version of the program, it'll show you what scale needs to be selected in game for it to work properly. Unless more information surfaces, I can't pinpoint any bugs, as you're the only one having said issues

**Comment by ajuanjojjj** [comment]
Just tried the new version, and it seems to be working fine, although it crashed when i loaded the C Major midi, i should be able to send some logs if you want them, just need to know if they're located somewhere :P

**Comment by ianespana** [comment]
Was it a crash (program closed unexpectedly) or was it a warning from Windows about "The program has stopped responding"?
If it's the former then it's a new issue, if it's the latter I'd need to know if you clicked the play button when Warframe wasn't open

**Comment by ajuanjojjj** [comment]
Its a proper crash, Im assuming it might be related to the new track selection menu, but I can only speculate. All the other midis I tried worked fine, its just the simple chord ones, but at least is easily reproducible. I've uploaded 3 of them, hopefully you you can debug them, if you can't just tell me how to get some logs and ill post them asap :)

[Chords.zip](https://github.com/ianespana/ShawzinBot/files/5272081/Chords.zip)

**Comment by ianespana** [comment]
I'll give it a look after I push the new version in a bit
