### ISSUE TITLE
ShawzinBot doesn't seem to work at all

### ISSUE THREAD

**Issue by SgerbwdGwyn** [ianespana/ShawzinBot#33]
For reference I am using a simple test MIDI file (Mary had a little lamb), and although it plays back through the interface fine, it does absolutely nothing but open Warframe. For reference, I have the Tiamat Shawzin equipped and ready, with both the number keys and mouse buttons mapped to the strings, and the arrow keys and N-L-M mapped to the frets, but no input attempt is being made by Shawzin Bot.

The scales are matched, no MIDI input device is selected (as none are available), and under MIDI tracks I have the option of toggling "piano" which I leave toggled on.

I am running it as administrator, and have tried it using other MIDI files too - is there some part of the config I am missing completely?

**Comment by ianespana** [comment]
2.2.1 had a bug were keys weren't being sent correctly to the game. Try the latest release (2.2.2), should be fixed
