### ISSUE TITLE
Immediate crash with newest version

### ISSUE THREAD

**Issue by Kamasu-Tra** [ianespana/ShawzinBot#34]
As title says, the newest release of ShawzinBot immediately crashes on my system. Running Windows 7 64bit, and the previous version still works fine. Really happy to see this getting an update; I play around with it nearly daily, and have got a nice collection of MIDI's I play to my clan and squadmates, so thanks for making a wicked piece of kit!

Here is the crash log that windows spat at me:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	ShawzinBot.exe
  Problem Signature 02:	2.2.2.3
  Problem Signature 03:	94504a0b
  Problem Signature 04:	System
  Problem Signature 05:	4.8.4001.0
  Problem Signature 06:	5d37b3ae
  Problem Signature 07:	a25
  Problem Signature 08:	21a
  Problem Signature 09:	N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by ianespana** [comment]
I haven't been able to reproduce this yet. We'll have to wait for more info to come up, as I have no idea what's making it crash

**Comment by niktr** [comment]
Does it crash on launch or when you open a MIDI?
if on Open, can you check if your MIDI has only 1 track?
if yes, Select all the notes from Track0 , make a new Track and Move all the notes to Track1.

**Comment by Kamasu-Tra** [comment]
It crashes immediately after launching, do not even have the chance to open
a MIDI file. I have also tried using my old config settings from the
previous version, but still no luck.

**Comment by niktr** [comment]
no idea then.
I guess try run as admin, compatibility mode or extracting it somewhere else like Desktop.
Or try running it on Win10. There might be a compatibility issue with win7.

**Comment by Kamasu-Tra** [comment]
Running as admin or in compatibility mode does not change anything, and I
don't have a Win10 system to do a test with. Are there any logs/reports
that Shawzin bot generates somewhere that might give us more info?
