### ISSUE TITLE
ShawzinBot needs to be closed and then re-opened to play midis in tune again

### ISSUE THREAD

**Issue by WMan22** [ianespana/ShawzinBot#35]
If you play a midi to the end with Shawzinbot or pause it in the middle of the song, then play that same midi or any other midi, it will play out of tune even if you switch to chromatic again first. It works the first time, but it is kind of annoying to have to relaunch ShawzinBot every time you load up a new midi for it to work properly.

This has been an issue since the Yo scale was added in 2.1, if that's helpful information.

**Comment by ianespana** [comment]
You don't need to switch back to Chromatic, you need to make sure the scale in game matches the one indicated by the program
