### ISSUE TITLE
Playing fast paces songs/songs with lots of notes lagging game

### ISSUE THREAD

**Issue by MediMouse** [ianespana/ShawzinBot#7]
When playing something like "Through Fire and Flames" the game will begin to heavily lag, even bugging the audio at times. is there a way to fix this, weather it be through the bot itself or in-game? 

note: my game usually runs around 120fps. but when playing the songs that have many notes, it can go down to only 1-7fps

**Comment by ianespana** [comment]
Can you send me the MIDI file? You're probably trying to play way too many notes at the same time
