### ISSUE TITLE
MIDI Input dropdown menu not rendering on top

### ISSUE THREAD

**Issue by Kisutora** [ianespana/ShawzinBot#8]
![ShawzinBot_n7D7kh1KwH](https://user-images.githubusercontent.com/22685232/64450102-1123e300-d0ea-11e9-8fa1-ce51bd4bc7ae.png)

**Comment by ianespana** [comment]
Noted, just need to fix the transparency

**Comment by ianespana** [comment]
Fixed in commit 8d8c8c3f76c73822a636b1d6163d6b2f14b947f5
